version: 2
jobs:
  build_and_pack:
    docker:
      - image: veimox/qtc:xenial-4.9.2
    steps:
      - checkout
      - run: cp -r . $BASE_PATH/ros_qtc_plugin
      - run: ls $BASE_PATH
      - run: .circleci/scripts/build.bash
      - run: .circleci/scripts/package.bash
      - store_artifacts:
          path: /tmp/abcdefghijklmnopqrstuvwxyz/installer/qtcreator-ros-xenial-latest-offline-installer.run
      - store_artifacts:
          path: /tmp/abcdefghijklmnopqrstuvwxyz/installer/qtcreator-ros-xenial-latest-online-installer.run
workflows:
  version: 2
  build_and_pack:
    jobs:
      - build_and_pack
